version: "3.8"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - sqlite_data:/app
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - API_URL=${API_URL:-http://backend:8000}
    networks:
      - app-network

volumes:
  sqlite_data:

networks:
  app-network:
    driver: bridge
